# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: check-yaml
- repo: https://github.com/ambv/black
  rev: 21.7b0
  hooks:
  - id: black
    files: ^MODAK/
- repo: https://github.com/pycqa/isort
  rev: 5.8.0
  hooks:
  - id: isort
    name: isort (python)
    files: ^MODAK/
