version: "2"
services:
  restapi:
    build: ./MODAK
    restart: unless-stopped
    image: modak-api
    ports:
      - "55000:5000"
    environment:
      MODAK_DATABASE_PASSWORD: my-very-secret-pw
      MODAK_DATABASE_HOST: modaksql
      MODAK_DATABASE_PORT: 3306

  modaksql:
    build: ./MODAK-DB
    restart: unless-stopped
    image: modak-py3-mysql
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: my-very-secret-pw
    volumes:
      - /docker-entrypoint-initdb.d/
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      timeout: 30s
      retries: 10
