image:
  name: quay.io/singularity/singularity:v3.4.2-slim
  entrypoint: [""]

variables:
  DEFFILE: "benchmarks"

build image:
  stage: deploy

  script:
    - apk update && apk upgrade && apk add bash
    - /bin/bash .gitlabci/build.sh build/${DEFFILE}.def
    - mkdir -p singularity && mv build/${DEFFILE}.tar.bz2 singularity/
    - mkdir -p singularity && mv build/${DEFFILE}.def singularity/

  # Run CI only if the definition file has been changed
  only:
    refs:
      - master
      - devel
    changes:
      - build/benchmarks.def
      - build/Make.Linux
      - build/mpirank.c
      - build/beffio_flags.txt
      - build/hpccinf.txt

  artifacts:
    paths:
      - singularity/${DEFFILE}.tar.bz2
      - singularity/${DEFFILE}.def
