image:
  name: quay.io/singularity/singularity:v3.5.3-slim
  entrypoint: [""]

variables:
  DEFFILE: "benchmarks"

build image:
  stage: deploy

  script:
    - apk update && apk upgrade && apk add bash sudo
    - mkdir -p singularity
    - /bin/bash bin/build.sh MPICH
    - mv ${DEFFILE}.simg singularity/${DEFFILE}_MPICH.simg
    - /bin/bash bin/build.sh OpenMPI
    - mv ${DEFFILE}.simg singularity/${DEFFILE}_OpenMPI.simg
    - cp build/${DEFFILE}.def singularity/

  # Run CI only if the definition file has been changed
  only:
    refs:
      - master
      - devel
    changes:
      - build/benchmarks.def
      - build/benchmarks_conf.def
      - build/Make.Linux
      - build/mpirank.c
      - build/beffio_flags.txt
      - build/hpccinf.txt

  artifacts:
    paths:
      - singularity/${DEFFILE}_MPICH.simg
      - singularity/${DEFFILE}_OpenMPI.simg
      - singularity/${DEFFILE}.def
