version: "2"
services:
  restapi:
    build: .
    image: modakopt/modak:api
    links:
      - modaksql
    ports:
      - "5000:5000"

  modaksql:
    build: ./pyMODAK
    image: modakopt/modak:py3_mysql
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_HOST: 0.0.0.0
      MYSQL_ROOT_PASSWORD: my-secret-pw
    volumes:
      - /docker-entrypoint-initdb.d/
