#PBS -S /bin/bash
#PBS -A PROJECT_CODE
#PBS -N JOB_NAME
#PBS -j oe
#PBS -k eod
#PBS -m abe
#PBS -M EMAIL_ADDRESS
#PBS -q QUEUE_NAME
#PBS -l nodes=NUM_NODES:ppn=CORES_PER_NODE:gpus=NUM_GPUS,walltime=HH:MM:SS

#MODAK_PRE_STAGING

#MODAK_AUTOTUNING

#MODAK_ENV

MPIRUN EXE_NAME ARGUMENTS

#MODAK_POST_STAGING
tune ../test/job.pbs_tune.input

singularity exec $1 mpicc -o mpitest mpitest.c
singularity exec $1 mpic++ -o heat_mpi heat_mpi.cpp
singularity exec $1 mpifort -o random_mpi random_mpi.f90

OMPI_MCA_plm_rsh_agent=sh
singularity exec $1 mpirun -n 4 ./heat_mpi
singularity exec $1 mpirun -n 4 ./mpitest
singularity exec $1 mpirun -n 4 ./random_mpi
