---
- hosts: all
  become: yes

  tasks:
    - name: Install sample database
      copy:
        dest: "{{ path }}"
        src: modakdb.sql
    - name: Change permissions    
      file:
        path: "{{ path }}"
        mode: 0777        
    - name: Remove old database container
      docker_component:
        state: absent
        name: "{{ alias }}"