#PBS -S /bin/bash
#PBS -m abe
#PBS -M ksivalinga@cray.com
#PBS -l nodes=1:ppn=40:gpus=1,walltime=24:00:00

cd $PBS_O_WORKDIR

#TENSORFLOW
export PYTHONPATH=$PYTHONPATH:/mnt/nfs/home/karthee/AI/models
cd /mnt/nfs/home/karthee/AI/models/official/vision/image_classification 

#/usr/local/bin/singularity exec /mnt/nfs/home/karthee/sodalite/AI/containers/tensorflow_2.1_opt_source_xla python3 resnet/resnet_imagenet_main.py --data_dir=/mnt/nfs/home/karthee/AI/data/tf_records/train/ -batch_size=128 --train_epochs=3 --train_steps=10 --use_synthetic_data=false --num_gpus=0 --noenable_xla

#export TF_XLA_FLAGS="--tf_xla_auto_jit=2 --tf_xla_cpu_global_jit"
#export XLA_FLAGS="--xla_dump_to=/mnt/nfs/home/karthee/tmp/generated"
#/usr/local/bin/singularity exec /mnt/nfs/home/karthee/sodalite/AI/containers/tensorflow_2.1_opt_source_xla python3 resnet/resnet_imagenet_main.py --data_dir=~/AI/data/ --batch_size=128 --train_epochs=1 --train_steps=1000 --use_synthetic_data=true --num_gpus=0 --enable_xla

#/usr/local/bin/singularity exec --nv /mnt/nfs/home/karthee/sodalite/AI/containers/tensorflow_2.1.0-gpu-py3.sif python3 resnet/resnet_imagenet_main.py --data_dir=/mnt/nfs/home/karthee/AI/data/tf_records/train/ -batch_size=96 --train_epochs=3 --train_steps=10 --use_synthetic_data=false  --noenable_xla

#/usr/local/bin/singularity exec --nv /mnt/nfs/home/karthee/sodalite/AI/containers/tensorflow_2.1.0-gpu-py3.sif python3 resnet/resnet_imagenet_main.py --data_dir=/mnt/nfs/home/karthee/AI/data/tf_records/train/ -batch_size=96 --train_epochs=3 --train_steps=10 --use_synthetic_data=false  --enable_xla
#
/usr/local/bin/singularity exec --nv /mnt/nfs/home/karthee/sodalite/AI/containers/gpu_tensorflow_sourceopt python3 resnet/resnet_imagenet_main.py --data_dir=/mnt/nfs/home/karthee/AI/data/tf_records/train/ -batch_size=96 --train_epochs=3 --train_steps=10 --use_synthetic_data=false  --noenable_xla
/usr/local/bin/singularity exec --nv /mnt/nfs/home/karthee/sodalite/AI/containers/gpu_tensorflow_sourceopt python3 resnet/resnet_imagenet_main.py --data_dir=/mnt/nfs/home/karthee/AI/data/tf_records/train/ -batch_size=96 --train_epochs=3 --train_steps=10 --use_synthetic_data=false  --enable_xla
#PYTORCH
#cd /mnt/nfs/home/karthee/AI/pytorch/examples/imagenet 
#/usr/local/bin/singularity exec --nv /mnt/nfs/home/karthee/sodalite/AI/containers/pytorch_1.4-cuda10.1-cudnn7-devel  python3 main.py -a resnet50 --epochs 3 --batch-size 96 /mnt/nfs/home/karthee/AI/data/ILSVRC/Data/CLS-LOC/ 
